#!/usr/bin/env bash
script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
java -Xms2g -Xmx12g -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+AlwaysPreTouch -XX:+TieredCompilation -jar "$script_dir/app/build/libs/app.jar" "$@"
