#!/usr/bin/env bash
script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
java -XX:+UnlockExperimentalVMOptions \
-XX:+UseContainerSupport \
-XX:MaxRAMPercentage=100.0 \
-XX:InitialRAMPercentage=8.0 \
-XX:MinRAMPercentage=8.0 \
-XX:ActiveProcessorCount=$(nproc)\
 -jar "$script_dir/app/build/libs/app.jar" "$@"
