// native/build.gradle.kts

plugins {
    `c-library`
}

library {
    // Define the library name without prefix and extension
    baseName.set("ubigint_native")

    // Define target machines (adjust based on your target platforms)
    targetMachines.set(
        listOf(
            machines.linux.x86_64,
            machines.windows.x86_64,
            machines.macOS.x86_64
        )
    )

    // Specify linkage type
    linkage.set(listOf(Linkage.SHARED))

    // Source files for the native library
    sources {
        c {
            source {
                srcDir("src/main/c")
                include("**/*.c")
            }
            // Include the JNI headers generated by the Java project
            exportedHeaders {
                srcDir("../app/build/jni_headers")
            }
        }
    }
}

// Ensure that the native library builds after Java classes (to have headers ready)
tasks.named("compileDebugSharedLibraryC") {
    dependsOn(":app:classes")
}
